### ISSUE TITLE
[META] Project cleanup

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#303]
- [ ] Rework project files
  - [ ] Look into possibly using qbs or even cmake instead of qmake
    - qmake works and is proven to work. It's also well-documented. However, it is somewhat clunky to use.
    - cmake has good support for discovering system libraries on Windows
    - qbs is newer and poorly documented with few non-trivial examples
  - [ ] Make them less system-specific 
    - Use qmake builtins: http://stackoverflow.com/a/10058744/4190028
  - [ ] Make [MXE](https://mxe.cc) support less clunky
- [ ] Support [OS X cross compilation](https://github.com/tpoechtrager/osxcross)
- [ ] Eliminate backend subrepo
- [ ] Eliminate backend as a QML plugin 
- [ ] Use pkg-config on OS X, Linux, MXE
  - [ ] All 3 build systems from above support it
- [ ] Look into using NuGet on Windows to automatically fetch dependencies
  - Available: zlib, SDL2
  - Not available: libsamplerate, gstreamer

**Comment by athairus** [comment]
CMake looks promising. I've made some changes to the project as I designed the build files:
- QML files are now loose and get copied to the build directory: `build_folder/QML/Phoenix/what/ever.qml`
  - Got rid of qrc files
  - Need to write `qmldir` files for each folder so we can import using proper import statements instead of relative paths.
- On OS X, don't use app bundles for development. It's less annoying to just have the executable sit in a folder that I don't have to right-click to access. I'll write scripts to put it into a `.app` bundle for distribution later on.

**Comment by athairus** [comment]
Reddit comment:
> If you are absolutely, positively, unconditionally convinced that you project will only ever run on one OS, go ahead and use whatever facilities that OS affords you. If, on the other hand, you're project is cross-platform, check in pre-compiled libraries in your source tree under /thirdparty/[name]/[version/[platform].
Trust me on that one. Managing multiple package managers is not worth it.
It. Is. Not. Worth. It.

After looking at other projects, I'm inclined to agree. If Phoenix were Linux-only or Linux and OS X exclusive this would be much simpler, but with Windows being thrown in the complexity just balloons. Juggling multiple 3rd party plugins on Windows is *not fun*.

**Comment by ProfessorKaos64** [comment]
I started building the project with cmake, I suppose this is the thread to track? I won't report any errors right now from Linux, since it's not complete.

**Comment by athairus** [comment]
[Meson](http://mesonbuild.com/) is a promising CMake alternative. One thing I really like about them is how they're trialing their system [against many large projects](https://github.com/mesonbuild/meson/wiki/Trial%20conversions) and making changes or adding new features to make their system practical for large non-trivial projects. They also seem to have excellent documentation and lots of examples. Oh, and first-class Qt support!
